### ISSUE TITLE
Release for ReSharper 9.1

### ISSUE THREAD

**Issue by CompleteBrains** [citizenmatt/resharper-preview-tab#4]
Hello. 

I just want to say it will be nice to have your addin for last ReSharper release.

Anyway, thanks for your work.

**Comment by slowkot** [comment]
Hi,
the same for me and could you please add vs 2015 support?
Thanks

**Comment by citizenmatt** [comment]
9.1 changed some of the behaviour around the preview tab - it's using it in more places. I hadn't spent the time to see if it's still needed. Short answer is yes, I think it is. I'll get a new build up in the next couple of days.

If you're interested, here's where ReSharper uses the preview tab:

* The various tree views, e.g. Find Results, will open in the preview tab if you navigate by pressing enter, and if you're holding shift while double clicking. It does NOT use preview tab if you press control+enter, to switch focus
* Navigating to external sources is opened in preview tab
* Navigating to files (under certain circumstances) opens in preview tabs

Plenty more places it could/should be used, IMHO.

**Comment by CompleteBrains** [comment]
@citizenmatt Thank you for clarifications and new build.

**Comment by citizenmatt** [comment]
Just pushed a version to the extension gallery. You should be able to download it from ReSharper &rarr; Extension Manager.

**Comment by citizenmatt** [comment]
Oh, and it supports VS2015, too.

**Comment by CompleteBrains** [comment]
@citizenmatt Thank you very much.

**Comment by slowkot** [comment]
Cool! Many thanks @CompleteBrains!

**Comment by CompleteBrains** [comment]
@slowkot You have mistaken I guess

**Comment by slowkot** [comment]
Yep, many thanks to @citizenmatt!
And thanks to you too =)

**Comment by citizenmatt** [comment]
Yay! Thanks to everyone! :smile:

**Comment by Brains** [comment]
I got that in `WinForms` they look almost the same, just different data is used for the indicators
But do you want me to replicate completely the same design in `WPF` or I can try to create something slightly different but with all that info from `WinForms` of course?
<sub>[View in Slack](https://officeautomata.slack.com/archives/GGNQW4CMV/p1559727516003500)</sub>
