### ISSUE TITLE
Resharper 9.2 support

### ISSUE THREAD

**Issue by AlexEndris** [citizenmatt/resharper-preview-tab#5]
Would be great if this was possible. I can't see the extension in Resharper's Extension Manager now. I'm using it in conjunction with VS 2015.

**Comment by citizenmatt** [comment]
Oops. I'd updated it for 9.2 RC2, and forgot to rebuild it for RTM. It's done now, and pushed to the gallery. Get it from ReSharper &rarr; Extension Manager.

**Comment by AlexEndris** [comment]
Thanks a lot! :) :+1:
