### ISSUE TITLE
R# 2017.1 support

### ISSUE THREAD

**Issue by zvirja** [citizenmatt/resharper-preview-tab#8]
Please add R# 2017.1 support. Somebody had to create this traditional issue 😉

**Comment by citizenmatt** [comment]
Nope. Not going to fix it.

Because it's in the product now! :smile:

<img width="1680" alt="screen shot 2017-04-04 at 8 59 51 am" src="https://cloud.githubusercontent.com/assets/222659/24646833/2c0ba840-1915-11e7-965a-8841c944c0b7.png">

I'll update the readme shortly.

**Comment by zvirja** [comment]
Wow, that's great! One less extension we need to install on each upgrade! :)
